//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach_MyClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDe
    {
        public int MaCD { get; set; }
        public string TenCD { get; set; }
    }
}
