//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach_MyClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> TinhTrangGiaoHang { get; set; }
        public Nullable<int> DaThanhToan { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaKH { get; set; }
    }
}
